name: NASA Project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js LTS version
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      - run: npm install
      - run: npm install --prefix client
      - run: npm run build --prefix client
